
package com.oopProj.form;
import com.oopProj.form.formula_buttons.Basics_btn;
import com.oopProj.form.formula_buttons.Diodes_btn;
import com.oopProj.form.formula_buttons.Transistors_btn;
import com.oopProj.form.formula_buttons.Cascaded_btn;
import com.oopProj.form.formula_buttons.ad1_btn;
import com.oopProj.form.formula_buttons.ad2_btn;
import com.oopProj.form.formula_buttons.ad3_btn;

import javax.swing.*;
/**
 *
 * @author LENOVO
 */
public class Formulas extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Formulas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        cascaded = new javax.swing.JButton();
        basics = new javax.swing.JButton();
        diodes = new javax.swing.JButton();
        transistors = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ad2 = new javax.swing.JButton();
        ad1 = new javax.swing.JButton();
        ad3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(245, 245, 245));

        cascaded.setBackground(new java.awt.Color(153, 145, 203));
        cascaded.setText("Cascaded Systems");
        cascaded.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cascaded.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cascaded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cascadedActionPerformed(evt);
            }
        });

        basics.setBackground(new java.awt.Color(153, 145, 203));
        basics.setText("Basics");
        basics.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        basics.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        basics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basicsActionPerformed(evt);
            }
        });

        diodes.setBackground(new java.awt.Color(153, 145, 203));
        diodes.setText("Diode Application");
        diodes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        diodes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diodes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diodesActionPerformed(evt);
            }
        });

        transistors.setBackground(new java.awt.Color(153, 145, 203));
        transistors.setText("Transistors");
        transistors.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        transistors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transistors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transistorsActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formula_contents/icon.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formula_contents/Additionals_text.png"))); // NOI18N

        ad2.setBackground(new java.awt.Color(215, 208, 255));
        ad2.setText("Measurement Units");
        ad2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ad2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad2ActionPerformed(evt);
            }
        });

        ad1.setBackground(new java.awt.Color(215, 208, 255));
        ad1.setText("Unit Conversions");
        ad1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ad1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad1ActionPerformed(evt);
            }
        });

        ad3.setBackground(new java.awt.Color(215, 208, 255));
        ad3.setText("International System Prefixes");
        ad3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ad3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ad3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/12 (1).png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/17.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(basics, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(diodes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(transistors, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cascaded, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ad3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basics, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diodes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transistors, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cascaded, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ad1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ad2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ad3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cascadedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cascadedActionPerformed
        Cascaded_btn f4 = new Cascaded_btn();
        f4.setLocationRelativeTo(null);
        f4.setVisible(true);
    }//GEN-LAST:event_cascadedActionPerformed

    private void diodesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diodesActionPerformed
        Diodes_btn f2 = new Diodes_btn();
        f2.setLocationRelativeTo(null);
        f2.setVisible(true);
    }//GEN-LAST:event_diodesActionPerformed

    private void transistorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transistorsActionPerformed
        Transistors_btn f3 = new Transistors_btn();
        f3.setLocationRelativeTo(null);
        f3.setVisible(true);
    }//GEN-LAST:event_transistorsActionPerformed

    private void basicsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basicsActionPerformed
        Basics_btn f1 = new Basics_btn();
        f1.setLocationRelativeTo(null);
        f1.setVisible(true);
    }//GEN-LAST:event_basicsActionPerformed

    private void ad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad2ActionPerformed
        ad2_btn a2 = new ad2_btn();
        a2.setLocationRelativeTo(null);
        a2.setVisible(true);
    }//GEN-LAST:event_ad2ActionPerformed

    private void ad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad1ActionPerformed
        ad1_btn a1 = new ad1_btn();
        a1.setLocationRelativeTo(null);
        a1.setVisible(true);
    }//GEN-LAST:event_ad1ActionPerformed

    private void ad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad3ActionPerformed
        ad3_btn a3 = new ad3_btn();
        a3.setLocationRelativeTo(null);
        a3.setVisible(true);
    }//GEN-LAST:event_ad3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ad1;
    private javax.swing.JButton ad2;
    private javax.swing.JButton ad3;
    private javax.swing.JButton basics;
    private javax.swing.JButton cascaded;
    private javax.swing.JButton diodes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton transistors;
    // End of variables declaration//GEN-END:variables
}
