/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.oopProj.form;

import com.oopProj.form.LibraryWindows.Lesson1;
import com.oopProj.form.LibraryWindows.Lesson2;
import com.oopProj.form.LibraryWindows.Lesson3;
import com.oopProj.form.LibraryWindows.Lesson4;
import com.oopProj.form.LibraryWindows.Lesson5;
import com.oopProj.form.LibraryWindows.Lesson6;
import com.oopProj.form.LibraryWindows.Lesson7;
import com.oopProj.form.LibraryWindows.Lesson8;
import com.oopProj.form.LibraryWindows.Lesson9;
import com.oopProj.form.LibraryWindows.Lesson10;
import com.oopProj.form.LibraryWindows.Lesson11;
import com.oopProj.form.LibraryWindows.Lesson12;
import com.oopProj.form.LibraryWindows.Lesson13;
import com.oopProj.form.LibraryWindows.Lesson14;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class Library extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Library() {
        initComponents();
        
        Lesson1Button.addActionListener(e -> openLesson1());
        Lesson2Button.addActionListener(e -> openLesson2());
        Lesson3Button.addActionListener(e -> openLesson3());
        Lesson4Button.addActionListener(e -> openLesson4());
        Lesson5Button.addActionListener(e -> openLesson5());
        Lesson6Button.addActionListener(e -> openLesson6());
        Lesson7Button.addActionListener(e -> openLesson7());
        Lesson8Button.addActionListener(e -> openLesson8());
        Lesson9Button.addActionListener(e -> openLesson9());
        Lesson10Button.addActionListener(e -> openLesson10());
        Lesson11Button.addActionListener(e -> openLesson11());
        Lesson12Button.addActionListener(e -> openLesson12());
        Lesson13Button.addActionListener(e -> openLesson13());
        Lesson14Button.addActionListener(e -> openLesson14());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Color theColor = new Color(215, 208, 255);
        jPanel1 = new RoundedPanel1(30, theColor);
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        Lesson1Button = new javax.swing.JButton();
        Lesson2Button = new javax.swing.JButton();
        Lesson3Button = new javax.swing.JButton();
        Lesson4Button = new javax.swing.JButton();
        Lesson5Button = new javax.swing.JButton();
        Lesson6Button = new javax.swing.JButton();
        Lesson7Button = new javax.swing.JButton();
        Lesson8Button = new javax.swing.JButton();
        Lesson9Button = new javax.swing.JButton();
        Lesson10Button = new javax.swing.JButton();
        Lesson11Button = new javax.swing.JButton();
        Lesson12Button = new javax.swing.JButton();
        Lesson13Button = new javax.swing.JButton();
        Lesson14Button = new javax.swing.JButton();
        Color theColor2 = new Color(236, 234, 248);
        libraryPanel = new RoundedPanel1(30, theColor2);

        setBackground(new java.awt.Color(245, 245, 245));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Istok Web", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Library");

        jPanel2.setBackground(new java.awt.Color(215, 208, 255));

        Lesson1Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson1Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson1Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson1Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons1.png"))); // NOI18N
        Lesson1Button.setText("Introduction to Semiconductors");
        Lesson1Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson1Button.setIconTextGap(5);
        Lesson1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson1ButtonActionPerformed(evt);
            }
        });

        Lesson2Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson2Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson2Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson2Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons2.png"))); // NOI18N
        Lesson2Button.setText("Semiconductor Diode");
        Lesson2Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson2Button.setIconTextGap(5);
        Lesson2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson2ButtonActionPerformed(evt);
            }
        });

        Lesson3Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson3Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson3Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson3Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons3.png"))); // NOI18N
        Lesson3Button.setText("Diode Application");
        Lesson3Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson3Button.setIconTextGap(5);
        Lesson3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson3ButtonActionPerformed(evt);
            }
        });

        Lesson4Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson4Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson4Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson4Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons4.png"))); // NOI18N
        Lesson4Button.setText("Transistor Basics and Biasing");
        Lesson4Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson4Button.setIconTextGap(5);
        Lesson4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson4ButtonActionPerformed(evt);
            }
        });

        Lesson5Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson5Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson5Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson5Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons5.png"))); // NOI18N
        Lesson5Button.setText("Transistor Amplifier Circuit Analysis");
        Lesson5Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson5Button.setIconTextGap(5);
        Lesson5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson5ButtonActionPerformed(evt);
            }
        });

        Lesson6Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson6Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson6Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson6Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons6.png"))); // NOI18N
        Lesson6Button.setText("Frequency Response");
        Lesson6Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson6Button.setIconTextGap(5);
        Lesson6Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson6ButtonActionPerformed(evt);
            }
        });

        Lesson7Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson7Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson7Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson7Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons8.png"))); // NOI18N
        Lesson7Button.setText("Transistor Small Signal Amplifiers");
        Lesson7Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson7Button.setIconTextGap(5);
        Lesson7Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson7ButtonActionPerformed(evt);
            }
        });

        Lesson8Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson8Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson8Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson8Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons9.png"))); // NOI18N
        Lesson8Button.setText("Op-Amp Application");
        Lesson8Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson8Button.setIconTextGap(5);
        Lesson8Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson8ButtonActionPerformed(evt);
            }
        });

        Lesson9Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson9Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson9Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson9Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons10.png"))); // NOI18N
        Lesson9Button.setText("Introduction to Feedback System");
        Lesson9Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson9Button.setIconTextGap(5);
        Lesson9Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson9ButtonActionPerformed(evt);
            }
        });

        Lesson10Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson10Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson10Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson10Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons11.png"))); // NOI18N
        Lesson10Button.setText("Passive Filters");
        Lesson10Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson10Button.setIconTextGap(5);
        Lesson10Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson10ButtonActionPerformed(evt);
            }
        });

        Lesson11Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson11Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson11Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson11Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons12.png"))); // NOI18N
        Lesson11Button.setText("Active Filters");
        Lesson11Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson11Button.setIconTextGap(5);
        Lesson11Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson11ButtonActionPerformed(evt);
            }
        });

        Lesson12Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson12Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson12Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson12Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons13.png"))); // NOI18N
        Lesson12Button.setText("Oscillators");
        Lesson12Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson12Button.setIconTextGap(5);
        Lesson12Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson12ButtonActionPerformed(evt);
            }
        });

        Lesson13Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson13Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson13Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson13Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons14.png"))); // NOI18N
        Lesson13Button.setText("DACs and ADCs");
        Lesson13Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson13Button.setIconTextGap(5);
        Lesson13Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson13ButtonActionPerformed(evt);
            }
        });

        Lesson14Button.setBackground(new java.awt.Color(185, 177, 238));
        Lesson14Button.setFont(new java.awt.Font("Istok Web", 1, 14)); // NOI18N
        Lesson14Button.setForeground(new java.awt.Color(0, 0, 0));
        Lesson14Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryIcons/libraryIcons15.png"))); // NOI18N
        Lesson14Button.setText("Digital Integrated Circuits");
        Lesson14Button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lesson14Button.setIconTextGap(5);
        Lesson14Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lesson14ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Lesson13Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson1Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson2Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson3Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson4Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson5Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson6Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson7Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson8Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson9Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson12Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson11Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson10Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lesson14Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lesson1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lesson2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson6Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson7Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson8Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson9Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson10Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson11Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson12Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson13Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Lesson14Button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        libraryPanel.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout libraryPanelLayout = new javax.swing.GroupLayout(libraryPanel);
        libraryPanel.setLayout(libraryPanelLayout);
        libraryPanelLayout.setHorizontalGroup(
            libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        libraryPanelLayout.setVerticalGroup(
            libraryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libraryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(libraryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

        private void openLesson1() {
        libraryPanel.removeAll();
        Lesson1 lesson1frame = new Lesson1();
        libraryPanel.add(lesson1frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson2() {
        libraryPanel.removeAll();
        Lesson2 lesson2frame = new Lesson2();
        libraryPanel.add(lesson2frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson3() {
        libraryPanel.removeAll();
        Lesson3 lesson3frame = new Lesson3();
        libraryPanel.add(lesson3frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson4() {
        libraryPanel.removeAll();
        Lesson4 lesson4frame = new Lesson4();
        libraryPanel.add(lesson4frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson5() {
        libraryPanel.removeAll();
        Lesson5 lesson5frame = new Lesson5();
        libraryPanel.add(lesson5frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson6() {
        libraryPanel.removeAll();
        Lesson6 lesson6frame = new Lesson6();
        libraryPanel.add(lesson6frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson7() {
        libraryPanel.removeAll();
        Lesson7 lesson7frame = new Lesson7();
        libraryPanel.add(lesson7frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson8() {
        libraryPanel.removeAll();
        Lesson8 lesson8frame = new Lesson8();
        libraryPanel.add(lesson8frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson9() {
        libraryPanel.removeAll();
        Lesson9 lesson9frame = new Lesson9();
        libraryPanel.add(lesson9frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson10() {
        libraryPanel.removeAll();
        Lesson10 lesson10frame = new Lesson10();
        libraryPanel.add(lesson10frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson11() {
        libraryPanel.removeAll();
        Lesson11 lesson11frame = new Lesson11();
        libraryPanel.add(lesson11frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson12() {
        libraryPanel.removeAll();
        Lesson12 lesson12frame = new Lesson12();
        libraryPanel.add(lesson12frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson13() {
        libraryPanel.removeAll();
        Lesson13 lesson13frame = new Lesson13();
        libraryPanel.add(lesson13frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
        private void openLesson14() {
        libraryPanel.removeAll();
        Lesson14 lesson14frame = new Lesson14();
        libraryPanel.add(lesson14frame.getContentPane());
        libraryPanel.revalidate();
        libraryPanel.repaint();
    }
    private void Lesson2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson2ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson2ButtonActionPerformed

    private void Lesson1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson1ButtonActionPerformed

    private void Lesson3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson3ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson3ButtonActionPerformed

    private void Lesson4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson4ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson4ButtonActionPerformed

    private void Lesson5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson5ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson5ButtonActionPerformed

    private void Lesson6ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson6ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson6ButtonActionPerformed

    private void Lesson7ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson7ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson7ButtonActionPerformed

    private void Lesson8ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson8ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson8ButtonActionPerformed

    private void Lesson9ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson9ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson9ButtonActionPerformed

    private void Lesson10ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson10ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson10ButtonActionPerformed

    private void Lesson11ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson11ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson11ButtonActionPerformed

    private void Lesson12ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson12ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson12ButtonActionPerformed

    private void Lesson13ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson13ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson13ButtonActionPerformed

    private void Lesson14ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lesson14ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lesson14ButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lesson10Button;
    private javax.swing.JButton Lesson11Button;
    private javax.swing.JButton Lesson12Button;
    private javax.swing.JButton Lesson13Button;
    private javax.swing.JButton Lesson14Button;
    private javax.swing.JButton Lesson1Button;
    private javax.swing.JButton Lesson2Button;
    private javax.swing.JButton Lesson3Button;
    private javax.swing.JButton Lesson4Button;
    private javax.swing.JButton Lesson5Button;
    private javax.swing.JButton Lesson6Button;
    private javax.swing.JButton Lesson7Button;
    private javax.swing.JButton Lesson8Button;
    private javax.swing.JButton Lesson9Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel libraryPanel;
    // End of variables declaration//GEN-END:variables
}

class RoundedPanel1 extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel1(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel1(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel1(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel1(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }