/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oopProj.form.EducVids_SubWindows;

import java.awt.Desktop;
import java.net.URL;

/**
 *
 * @author shy
 */
public class AllLessons extends javax.swing.JFrame {

    /**
     * Creates new form AllLessons
     */
    public AllLessons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        vid1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vid12 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        vid13 = new javax.swing.JButton();
        vid14 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        vid15 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        vid16 = new javax.swing.JButton();
        vid17 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        vid18 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        vid19 = new javax.swing.JButton();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        vid20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vid1.setBackground(new java.awt.Color(242, 242, 242));
        vid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid1.png"))); // NOI18N
        vid1.setBorder(null);
        vid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(88, 109, 165));
        jLabel2.setText("Introduction to Circuits");

        jLabel5.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(88, 109, 165));
        jLabel5.setText("\"GCSE Physics - Intro to circuits #14\"");

        jLabel1.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 109, 165));
        jLabel1.setText("By: Cognito");

        vid12.setBackground(new java.awt.Color(242, 242, 242));
        vid12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid2.png"))); // NOI18N
        vid12.setBorder(null);
        vid12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid12ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(88, 109, 165));
        jLabel34.setText("Fundamentals: Ohm's Law");

        jLabel35.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(88, 109, 165));
        jLabel35.setText("\"Ohms Law Explained - The basics circuit theory\"");

        jLabel36.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(88, 109, 165));
        jLabel36.setText("By: The Engineering Mindset");

        jLabel37.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(88, 109, 165));
        jLabel37.setText("Fundamentals: KVL & KCL");

        jLabel38.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(88, 109, 165));
        jLabel38.setText("\"Simplest Explanation of KIRCHHOFF'S LAWS (kcl kvl)\"");

        jLabel39.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(88, 109, 165));
        jLabel39.setText("By: Academic Fight");

        vid13.setBackground(new java.awt.Color(242, 242, 242));
        vid13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid3.png"))); // NOI18N
        vid13.setBorder(null);
        vid13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid13ActionPerformed(evt);
            }
        });

        vid14.setBackground(new java.awt.Color(242, 242, 242));
        vid14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid5.png"))); // NOI18N
        vid14.setBorder(null);
        vid14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid14ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(88, 109, 165));
        jLabel40.setText("Introduction to ECE: Electronic Components");

        jLabel41.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(88, 109, 165));
        jLabel41.setText("\"Electronic Components Guide\"");

        jLabel42.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(88, 109, 165));
        jLabel42.setText("By: GalcoTV");

        vid15.setBackground(new java.awt.Color(242, 242, 242));
        vid15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid6.png"))); // NOI18N
        vid15.setBorder(null);
        vid15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid15ActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(88, 109, 165));
        jLabel43.setText("Introduction to ECE: Semiconductors");

        jLabel44.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(88, 109, 165));
        jLabel44.setText("\"What Is A Semiconductor?\"");

        jLabel45.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(88, 109, 165));
        jLabel45.setText("By: MITK12Videos");

        jLabel46.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(88, 109, 165));
        jLabel46.setText("Introduction to ECE: Classification");

        jLabel47.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(88, 109, 165));
        jLabel47.setText("\"Classification of Semiconductors (Intrinsic/Extrinsic, P-Type/N-Type)\"");

        jLabel48.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(88, 109, 165));
        jLabel48.setText("By: CircuitBread");

        vid16.setBackground(new java.awt.Color(242, 242, 242));
        vid16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid7.png"))); // NOI18N
        vid16.setBorder(null);
        vid16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid16ActionPerformed(evt);
            }
        });

        vid17.setBackground(new java.awt.Color(242, 242, 242));
        vid17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid8.png"))); // NOI18N
        vid17.setBorder(null);
        vid17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid17ActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(88, 109, 165));
        jLabel49.setText("Diodes");

        jLabel50.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(88, 109, 165));
        jLabel50.setText("\"DIODES! All Sorts of Them and How They Work (ElectroBOOM101-010)\"");

        jLabel51.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(88, 109, 165));
        jLabel51.setText("By: ElectroBOOM");

        jLabel52.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(88, 109, 165));
        jLabel52.setText("\"Transistors Explained - How transistors work\"");

        jLabel53.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(88, 109, 165));
        jLabel53.setText("By: The Engineering Mindset");

        vid18.setBackground(new java.awt.Color(242, 242, 242));
        vid18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid9.png"))); // NOI18N
        vid18.setBorder(null);
        vid18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid18ActionPerformed(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(88, 109, 165));
        jLabel54.setText("Transistors");

        vid19.setBackground(new java.awt.Color(242, 242, 242));
        vid19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid10.png"))); // NOI18N
        vid19.setBorder(null);
        vid19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid19ActionPerformed(evt);
            }
        });

        jLabel55.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(88, 109, 165));
        jLabel55.setText("Amplifiers");

        jLabel56.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(88, 109, 165));
        jLabel56.setText("\"Amplifier basics, Types & Characteristics | Basics of Electronics\"");

        jLabel57.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(88, 109, 165));
        jLabel57.setText("By: Gadgetronicx");

        jLabel58.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(88, 109, 165));
        jLabel58.setText("Op-Amps");

        jLabel59.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(88, 109, 165));
        jLabel59.setText("\"Intro to Op-Amps (Operational Amplifiers) | Basic Circuits\"");

        jLabel60.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel60.setForeground(new java.awt.Color(88, 109, 165));
        jLabel60.setText("By: CircuitBread");

        vid20.setBackground(new java.awt.Color(242, 242, 242));
        vid20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid11.png"))); // NOI18N
        vid20.setBorder(null);
        vid20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid14)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid15)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid16)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel46)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid17)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid19)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55)
                            .addComponent(jLabel56)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid20)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel60, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel58)
                            .addComponent(jLabel59)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid18)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel52))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addComponent(vid1))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel34)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel35)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel36)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid13)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel37)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel39)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(vid14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel40)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel41)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid15)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel43)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel44)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel45)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel47)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel48)
                        .addGap(27, 27, 27)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid17)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel50)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel51)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid18)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel54)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel52)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel53)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid19)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel55)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel56)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel57)))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vid20)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel58)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel59)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel60)
                        .addGap(20, 20, 20)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid1ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=R3hdaLpq2AA").toURI());
        }
        catch(Exception e)
        {}

    }//GEN-LAST:event_vid1ActionPerformed

    private void vid12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid12ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=HsLLq6Rm5tU").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid12ActionPerformed

    private void vid13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid13ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=ZDoyIghUI44").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid13ActionPerformed

    private void vid14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid14ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=N8_1wb0r0DQ").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid14ActionPerformed

    private void vid15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid15ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=gUmDVe6C-BU").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid15ActionPerformed

    private void vid16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid16ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=ErcH_OuCaNY").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid16ActionPerformed

    private void vid17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid17ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=l2y-w9aS98k").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid17ActionPerformed

    private void vid18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid18ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=J4oO7PT_nzQ").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid18ActionPerformed

    private void vid19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid19ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=qKlEuwQTVvg").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid19ActionPerformed

    private void vid20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid20ActionPerformed
        // TODO add your handling code here
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=fmRHDqcodS4").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllLessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllLessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllLessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllLessons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllLessons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton vid1;
    private javax.swing.JButton vid12;
    private javax.swing.JButton vid13;
    private javax.swing.JButton vid14;
    private javax.swing.JButton vid15;
    private javax.swing.JButton vid16;
    private javax.swing.JButton vid17;
    private javax.swing.JButton vid18;
    private javax.swing.JButton vid19;
    private javax.swing.JButton vid20;
    // End of variables declaration//GEN-END:variables
}
