/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oopProj.form.EducVids_SubWindows;

import java.awt.Desktop;
import java.net.URL;
/**
 *
 * @author shy
 */
public class ECE extends javax.swing.JFrame {

    /**
     * Creates new form ECE
     */
    public ECE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        vid5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        vid6 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        vid7 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        vid8 = new javax.swing.JButton();
        vid9 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        vid10 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        vid11 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabel27.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(88, 109, 165));
        jLabel27.setText("\"DIODES! All Sorts of Them and How They Work (ElectroBOOM101-010)\"");

        jLabel26.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(88, 109, 165));
        jLabel26.setText("By: ElectroBOOM");

        jLabel28.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(88, 109, 165));
        jLabel28.setText("Transistors");

        jLabel29.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(88, 109, 165));
        jLabel29.setText("By: The Engineering Mindset");

        jLabel30.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(88, 109, 165));
        jLabel30.setText("\"Transistors Explained - How transistors work\"");

        jLabel31.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(88, 109, 165));
        jLabel31.setText("Amplifiers");

        jLabel32.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(88, 109, 165));
        jLabel32.setText("By: Gadgetronicx");

        jLabel33.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(88, 109, 165));
        jLabel33.setText("\"Amplifier basics, Types & Characteristics | Basics of Electronics\"");

        jLabel3.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 109, 165));
        jLabel3.setText("Op-Amps");

        jLabel4.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 109, 165));
        jLabel4.setText("By: CircuitBread");

        jLabel6.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 109, 165));
        jLabel6.setText("\"Intro to Op-Amps (Operational Amplifiers) | Basic Circuits\"");

        jLabel16.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(88, 109, 165));
        jLabel16.setText("Introduction to ECE: Electronic Components");

        jLabel17.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(88, 109, 165));
        jLabel17.setText("By: GalcoTV");

        jLabel18.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(88, 109, 165));
        jLabel18.setText("\"Electronic Components Guide\"");

        vid5.setBackground(new java.awt.Color(242, 242, 242));
        vid5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid5.png"))); // NOI18N
        vid5.setBorder(null);
        vid5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid5ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(88, 109, 165));
        jLabel19.setText("Introduction to ECE: Semiconductors");

        vid6.setBackground(new java.awt.Color(242, 242, 242));
        vid6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid6.png"))); // NOI18N
        vid6.setBorder(null);
        vid6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid6ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(88, 109, 165));
        jLabel20.setText("By: MITK12Videos");

        vid7.setBackground(new java.awt.Color(242, 242, 242));
        vid7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid7.png"))); // NOI18N
        vid7.setBorder(null);
        vid7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid7ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(88, 109, 165));
        jLabel21.setText("\"What Is A Semiconductor?\"");

        vid8.setBackground(new java.awt.Color(242, 242, 242));
        vid8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid8.png"))); // NOI18N
        vid8.setBorder(null);
        vid8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid8ActionPerformed(evt);
            }
        });

        vid9.setBackground(new java.awt.Color(242, 242, 242));
        vid9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid9.png"))); // NOI18N
        vid9.setBorder(null);
        vid9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid9ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(88, 109, 165));
        jLabel22.setText("Introduction to ECE: Classification");

        jLabel24.setFont(new java.awt.Font("Istok Web", 3, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(88, 109, 165));
        jLabel24.setText("\"Classification of Semiconductors (Intrinsic/Extrinsic, P-Type/N-Type)\"");

        vid10.setBackground(new java.awt.Color(242, 242, 242));
        vid10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid10.png"))); // NOI18N
        vid10.setBorder(null);
        vid10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid10ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Istok Web", 0, 10)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(88, 109, 165));
        jLabel23.setText("By: CircuitBread");

        vid11.setBackground(new java.awt.Color(242, 242, 242));
        vid11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vid11.png"))); // NOI18N
        vid11.setBorder(null);
        vid11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vid11ActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Istok Web", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(88, 109, 165));
        jLabel25.setText("Diodes");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel33)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid11)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vid8)
                            .addComponent(vid9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel27)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid7)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid5)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addGap(23, 23, 23)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(vid6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel19)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(vid7)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addGap(21, 21, 21)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(vid8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(vid9)
                        .addGap(30, 30, 30)
                        .addComponent(vid10)
                        .addGap(30, 30, 30)
                        .addComponent(vid11)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel28)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel31)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(38, 38, 38))))
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vid5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid5ActionPerformed
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=N8_1wb0r0DQ").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid5ActionPerformed

    private void vid6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid6ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=gUmDVe6C-BU").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid6ActionPerformed

    private void vid7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid7ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=ErcH_OuCaNY").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid7ActionPerformed

    private void vid8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid8ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=l2y-w9aS98k").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid8ActionPerformed

    private void vid9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid9ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=J4oO7PT_nzQ").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid9ActionPerformed

    private void vid10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid10ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=qKlEuwQTVvg").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid10ActionPerformed

    private void vid11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vid11ActionPerformed
        // TODO add your handling code here:
        try{
            Desktop.getDesktop().browse(new URL("https://www.youtube.com/watch?v=fmRHDqcodS4").toURI());
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_vid11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ECE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ECE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ECE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ECE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ECE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton vid10;
    private javax.swing.JButton vid11;
    private javax.swing.JButton vid5;
    private javax.swing.JButton vid6;
    private javax.swing.JButton vid7;
    private javax.swing.JButton vid8;
    private javax.swing.JButton vid9;
    // End of variables declaration//GEN-END:variables
}
